site_name: Stefan Peele — Technical Documentation
site_url: https://stefanpeele.github.io/stefan-peele-docs
site_description: Network engineering lab documentation, 
  configurations, and technical references. .
site_author: Stefan Peele

repo_name: StefanPeele/stefan-peele-docs
repo_url: https://github.com/StefanPeele/stefan-peele-docs

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Router:
    - Overview: router/index.md
  - Switches:
    - Overview: switches/index.md
  - L3 Switch:
    - Overview: l3-switch/index.md
  - Firewall:
    - Overview: firewall/index.md
  - End Devices:
    - Proxmox:
      - Overview: end-devices/proxmox/index.md
    - Linux:
      - Overview: end-devices/linux/index.md
    - Windows:
      - Overview: end-devices/windows/index.md
    - Security:
      - Overview: end-devices/security/index.md
  - Setup:
    - Overview: setup/index.md
  - Reference:
    - Overview: reference/index.md
  - Expansion:
    - Overview: expansion/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables